import { QuizQuestion } from './types'

export const quizData: QuizQuestion[] = [
  // easy 
  {
    id: 1,
    quote: "It needs to be about 20% cooler.",
    characer: "Rainbow Dash",
    difficulty: "easy",
    options: ["Rainbow Dash", "Apple Jack", "Ember", "Pinkie Pie"],
    correctAnswer: 0,
  },
  {
    id: 2,
    quote: "And then I said oatmeal? Are you crazy?!",
    characer: "Twilight Sparkle",
    difficulty: "easy",
    options: ["Twilight Sparkle", "Pinkie Pie", "Celestia", "Big Mac"],
    correctAnswer: 0,
  },
  {
    id: 3,
    quote: "I don't like it. I don't like it one bit. I know smiles. And those smiles? They're just not right.",
    characer: "Pinkie Pie",
    difficulty: "easy",
    options: ["Pinkie Pie", "Scootaloo", "Silverstream", "Discord"],
    correctAnswer: 0,
  },
  {
    id: 4,
    quote: "My sister's speakin' in Fancy!",
    characer: "Apple Jack",
    difficulty: "easy",
    options: ["Apple Jack", "Celestia", "Pound Cake", "Sweetie Belle"],
    correctAnswer: 0,
  },
  {
    id: 5,
    quote: "I'm …just so…PEEVED",
    characer: "Fluttershy",
    difficulty: "easy",
    options: ["Fluttershy", "Rainbow Dash", "Maud Pie", "Rarity"],
    correctAnswer: 0,
  },
  {
    id: 6,
    quote: "My emotions darling!, stress couture!",
    characer: "Rarity",
    difficulty: "easy",
    options: ["Rarity", "Coco Pommel", "Discord", "Hoity Toity"],
    correctAnswer: 0,
  },

  // medium 
  {
    id: 7,
    quote: "Making sense? Oh, what fun is there in making sense?",
    characer: "Discord",
    difficulty: "medium",
    options: ["Discord", "Pinkie Pie", "Sweetie Belle", "Spike"],
    correctAnswer: 0,
  },
  {
    id: 8,
    quote: "Huzzah! How many points do I receive?",
    characer: "Princess Luna",
    difficulty: "medium",
    options: ["Princess Luna", "Discord", "Celestia", "Twilight Sparkle"],
    correctAnswer: 0,
  },
  {
    id: 9,
    quote: "I will never wash this cheek again.",
    characer: "Spike",
    difficulty: "medium",
    options: ["Spike", "Snips", "Snails", "Zephyr Breeze"],
    correctAnswer: 0,
  },
  {
    id: 10,
    quote: "I'm a year older than you.",
    characer: "Fluttershy",
    difficulty: "medium",
    options: ["Fluttershy", "Big Mac", "Rainbow Dash", "Twilight Sparkle"],
    correctAnswer: 0,
  },
  {
    id: 11,
    quote: "I just don't know what went wrong!",
    characer: "Derpy Hooves",
    difficulty: "medium",
    options: ["Derpy Hooves", "Dinky Hooves", "Dr. Whooves", "Carrot Top"],
    correctAnswer: 0,
  },
  {
    id: 12,
    quote: "I want to learn how to become a Cutie Mark Crusader... Because then I could get all my classmates to do me favors!",
    characer: "Pipsqueak",
    difficulty: "medium",
    options: ["Pipsqueak", "Silver Spoon", "Snips", "Snails"],
    correctAnswer: 0,
  },
  {
    id: 13,
    quote: "Quiet",
    characer: "Starlight Glimmer",
    difficulty: "medium",
    options: ["Starlight Glimmer", "Twilight Sparkle", "Princess Luna", "Fluttershy"],
    correctAnswer: 0,
  },

  // hard
  {
    id: 14,
    quote: "Oh, Fluttershy. You're such a loudmouth.",
    characer: "Fluttershy",
    difficulty: "hard",
    options: ["Fluttershy", "Rainbow Dash", "Starlight Glimmer", "Rarity"],
    correctAnswer: 0,
  },
  {
    id: 15,
    quote: "Just put the hay in the apple and eat the candle.",
    characer: "Twilight Sparkle",
    difficulty: "hard",
    options: ["Twilight Sparkle", "Pinkie Pie", "Discord", "Cheese Sandwich"],
    correctAnswer: 0,
  },
  {
    id: 16,
    quote: "Hey Twilight, what's soaking wet and clueless? Your face!",
    characer: "Fluttershy",
    difficulty: "hard",
    options: ["Fluttershy", "Rainbow Dash", "Discord", "Cozy Glow"],
    correctAnswer: 0,
  },
  {
    id: 17,
    quote: "You heards the lady, she ain't going nowheres chump!",
    characer: "Pinkie Pie",
    difficulty: "hard",
    options: ["Pinkie Pie", "Trixie", "Amber", "Daring Doo"],
    correctAnswer: 0,
  },
  {
    id: 18,
    quote: "To be honest, I'm a little out of practice when it comes to flying.",
    characer: "Princess Cadance",
    difficulty: "hard",
    options: ["Princess Cadance", "Twilight Sparkle", "Night Glider", "Rainbow Dash"],
    correctAnswer: 0,
  },

  // super hard 
  {
    id: 19,
    quote: "The fate of Equestria does not rest on my shoulders alone. It rests on all of ours.",
    characer: "Star Swirl the Bearded",
    difficulty: "super hard",
    options: ["Star Swirl the Bearded", "Celestia", "Chrysalis", "Twilight Sparkle"],
    correctAnswer: 0,
  },
  {
    id: 20,
    quote: "I have been away too long if my name no longer strikes fear into the heart of one so tiny.",
    characer: "Grogar",
    difficulty: "super hard",
    options: ["Grogar", "Discord", "Stygian", "Tirek"],
    correctAnswer: 0,
  },
  {
    id: 21,
    quote: "You can't let one bad apple make you think you failed.",
    characer: "Silverstream",
    difficulty: "super hard",
    options: ["Silverstream", "Apple Bloom", "Diamond Tiara", "Ocellus"],
    correctAnswer: 0,
  },
  {
    id: 22,
    quote: "Necklace. Necklace. Necklace. Necklace. AND... BIG Crown thingy!",
    characer: "Twilight Sparkle",
    difficulty: "super hard",
    options: ["Twilight Sparkle", "Trixie", "Discord", "Sunburst"],
    correctAnswer: 0,
  },
  {
    id: 23,
    quote: "Everypony should get fun gifts on their birthday!",
    characer: "Cheerilee",
    difficulty: "super hard",
    options: ["Cheerilee", "Pinkie Pie", "Fluttershy", "Cheese Sandwich"],
    correctAnswer: 0,
  },
  {
    id: 24,
    quote: "They've fled! Celestia and Luna are too cowardly to even stand against me! Equestria is mine!",
    characer: "Sombra",
    difficulty: "super hard",
    options: ["Sombra", "Chrysalis", "Lord Tirek", "Grogar"],
    correctAnswer: 0,
  },
  {
    id: 25,
    quote: "Oh, I'm sorry... that you actually bite into those tasteless, mealyworm-filled things.",
    characer: "Strawberry Sunrise",
    difficulty: "super hard",
    options: ["Strawberry Sunrise", "Berry Punch", "Daisy", "Lily Valley"],
    correctAnswer: 0,
  },
]
